# Generated by Django 4.2.6 on 2023-10-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0002_alter_pdf_ownerpdflist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='ownerPDFlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xeroxapp.ownerpdflist'),
        ),
    ]
