# Generated by Django 4.2.6 on 2023-11-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0003_alter_pdf_ownerpdflist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerpdflist',
            options={'verbose_name': 'ownerPDFlist', 'verbose_name_plural': 'ownerPDFlist'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFs'},
        ),
    ]
