# Generated by Django 4.2.6 on 2023-12-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0005_credentiallist_alter_ownerpdflist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentiallist',
            options={'verbose_name': 'CredentialList', 'verbose_name_plural': 'CredentialLists'},
        ),
    ]
