# Generated by Django 4.2.6 on 2023-12-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0006_alter_credentiallist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentiallist',
            options={'verbose_name': 'CredentialList'},
        ),
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Credentials'},
        ),
    ]
