# Generated by Django 4.2.6 on 2023-12-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0008_alter_credentiallist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pdf',
            name='Slno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
