# Generated by Django 4.2.6 on 2023-12-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0009_rename_text_pdf_name_pdf_slno_pdf_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='order',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
