# Generated by Django 4.2.6 on 2023-12-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0010_pdf_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='order',
        ),
        migrations.CreateModel(
            name='StudentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slno', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('order', models.BooleanField()),
                ('ownerPDFlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xeroxapp.ownerpdflist')),
            ],
            options={
                'verbose_name': 'StudentPDF',
                'verbose_name_plural': 'StudentPDFs',
            },
        ),
    ]
