# Generated by Django 4.2.6 on 2023-12-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0012_studentpdflist_remove_studentpdf_ownerpdflist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpdflist',
            options={'verbose_name_plural': 'studentPDFlist'},
        ),
    ]
