# Generated by Django 4.2.6 on 2023-12-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0013_alter_studentpdflist_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPDF',
        ),
        migrations.DeleteModel(
            name='studentPDFlist',
        ),
    ]
