# Generated by Django 4.2.6 on 2023-12-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0014_delete_studentpdf_delete_studentpdflist'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentPDFlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'studentPDFlist',
            },
        ),
        migrations.CreateModel(
            name='studentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slno', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('order', models.BooleanField()),
                ('studentPDFlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xeroxapp.studentpdflist')),
            ],
            options={
                'verbose_name': 'studentPDF',
                'verbose_name_plural': 'studentPDFs',
            },
        ),
    ]
