# Generated by Django 4.2.6 on 2023-12-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0016_ownerorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerorders',
            options={'verbose_name_plural': 'ownerorders'},
        ),
    ]
