# Generated by Django 4.2.6 on 2023-12-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0017_alter_ownerorders_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('CredentialList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xeroxapp.credentiallist')),
            ],
            options={
                'verbose_name_plural': 'OwnerCredentials',
            },
        ),
        migrations.DeleteModel(
            name='ownerorders',
        ),
    ]
