# Generated by Django 4.2.6 on 2023-12-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xeroxapp', '0018_ownercredentials_delete_ownerorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slno', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('ownerPDFlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xeroxapp.ownerpdflist')),
            ],
            options={
                'verbose_name_plural': 'OwnerOrder',
            },
        ),
    ]
