# Generated by Django 4.2.6 on 2024-01-06 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xeroxapp", "0020_rename_credentials_studentcredentials"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentcredentials",
            options={"verbose_name_plural": "StudentCredentials"},
        ),
    ]
